### PR TITLE
Fix crash on RMT driver initialization

### PR DESCRIPTION
**Pull request by dmitrymu**

### CODE REVIEW

**Comment by dmitrymu** [comment]
I'm sorry, David, created PR by mistake (instead of creating in in my own fork).

The crash is still real, I observe it when compiled with IDF SDK 4.1.3

**Comment by DavidAntliff** [comment]
Hi @dmitrymu, no problem, thank you for the PR.

How reproducible is the crash? Does it happen 100% of the time with SDK 4.1.3? I suspect that Espressif have moved their initialisation sequence around a bit, perhaps.

**Comment by dmitrymu** [comment]
For me it was stable under 4.1.3, and rmt.c, which is crashing (https://github.com/espressif/esp-idf/blob/release/v4.1/components/driver/rmt.c) did not change much in 4.4.2.

It crashes because rmt_set_source_clk() internally uses a structure which is initialized by rmt_driver_install().  Calling them in reverse order causes null pointer dereference.

**Comment by DavidAntliff** [comment]
Thank you!

**Pull request merged**
