### PR TITLE
Extract GPIO-fixup to separate function and add Pull-Up

### PR DESCRIPTION
**Pull request by niobos**
Extract the GPIO fiddling to a sepparate function. Additionally, enable
internal pull-ups, since it's not enabled by default on all pins.

I've tested this on ESP-IDF v3.3. The main difference I introduces is explicitly enable PullUp on the selected GPIO. The rest is more cosmetics.

### CODE REVIEW

**Comment by DavidAntliff** [comment]
Thanks for the PR. Just a few questions before I merge this:

1. have you had a chance to test this with multiple devices on the same one-wire bus in active powered mode?
2. the one-wire spec requires an external pull-up (e.g. 4k7 ohm). I understand that this value cannot be too high otherwise not enough current is provided to the bus. I believe the internal pull-up on the ESP32 is something like 30kohm or more, which is too high according to the one-wire bus spec. What's your intention with enabling the internal pull-up? Do you hope to use it instead of an external pullup?

I'd like to understand why you need the pull-up enabled, as having it enabled by default may interfere with the external pullup and be unexpected by other users.

**Comment by nielslaukens** [comment]
Hi David,

Thanks for the very quick response.

1. Yes, I tested this with two DS18B20 sensors attached in parallel (3-wires, no parasitic power) and it works.

2. Hmm, I did forget about that. Indeed, my setup did not have an external pull-up, and I abused the internal pull-up instead.

You are right that the internal pull-up should not be enabled, at least not by default. I'll try to rewrite this to make to make activating the pull-up optional.

**Comment by niobos** [comment]
Hi David,

Thanks for the very quick response.

1. Yes, I tested this with two DS18B20 sensors attached in parallel (3-wires, no parasitic power) and it works.

2. Hmm, I did forget about that. Indeed, my setup did not have an external pull-up, and I abused the internal pull-up instead.

You are right that the internal pull-up should not be enabled, at least not by default. I'll try to rewrite this to make to make activating the pull-up optional.

**Comment by DavidAntliff** [comment]
Hi @niobos I'll close this PR for now, please re-open it if you decide to revisit this functionality.

**Pull request closed without merging**
